name: Setup code-test enviroment

on:
  workflow_call:

jobs:
  setup:
    name: Create submission branch
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Check if current repo is a template
        id: not-template
        continue-on-error: true # Even if this is a template repo, we don't want this job to fail
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api repos/${{ github.repository }} | jq --exit-status '.is_template == false'

      - name: Checkout code
        if: steps.not-template.outcome == 'success'
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Create a development branch and commit changes to the repo
        if: steps.not-template.outcome == 'success'
        env:
          name: ðŸ‘¾ SaltBot
          email: noreply@salt.dev
          message: Good luck and have fun!
        run: |
          git config --global user.name '${{ env.name }}'
          git config --global user.email '${{ env.email }}'
          git branch Submission
          git push origin Submission
          
